### ISSUE TITLE
support additional queries other than connectivity-map

### ISSUE THREAD

**Issue by adisos** [np-guard/vpc-network-config-analyzer#64]
- [x] connectivity diff - see issue #163 
- [ ] permits/forbids 
- [ ] linting - see issue #116 
- [x] explainability - see issue #42

**Comment by zivnevo** [comment]
Closing for now
